#!/home/ben/software/install/bin/perl
use warnings;
use strict;
use utf8;
use CSS::Tidy 'tidy_css';

# To do: add a blank line after ^} if there is none.
#
#}
#.myclass {
#
#turns into
#
#}
#
#.myclass {

my $text = '';

while (<STDIN>) {
    $text .= $_;
}

my $out = tidy_css ($text);
print "$out\n";

# Local variables:
# mode: perl
# End:
